### ISSUE TITLE
Improvements in documentation

### ISSUE THREAD

**Issue by oinkbark** [googleapis/nodejs-iam-credentials#9]
## Remove from quickstart example:
```
// remove this line after package is released
// eslint-disable-next-line node/no-missing-require

//TODO(library generator): write the actual function you will be testing
```
## Add to quickstart example:
For the scope example, you should list "https://www.googleapis.com/auth/cloud-platform" instead of an undefined variable.
For the name example, you should list "ACCOUNT_EMAIL_OR_UNIQUEID" instead of an undefined variable called "serviceAccount".
For the name example, you should include the comment "The - wildcard character is required; replacing it with a project ID is invalid.".
For the service account example, you should include the comment "The service account must be granted the roles/iam.serviceAccountTokenCreator role."
For the token variable, it is missing the array destructuring brackets that the other libraries usually provide.

**Comment by JustinBeckwith** [comment]
@oinkbark I updated the name of the title - please check out our [Code of Conduct](https://github.com/googleapis/nodejs-iam-credentials/blob/master/CODE_OF_CONDUCT.md) to learn more.
